# Generated by Django 5.1.7 on 2025-03-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
    ]
