# Generated by Django 5.1.6 on 2025-03-01 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('lpa', models.CharField(blank=True, max_length=20, null=True)),
                ('jobtype', models.CharField(blank=True, max_length=30, null=True)),
                ('jobmode', models.CharField(blank=True, max_length=30, null=True)),
                ('experiance', models.CharField(blank=True, max_length=30, null=True)),
                ('applyBefore', models.DateField(blank=True, null=True)),
                ('posteDate', models.DateTimeField(auto_now_add=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('responsibility', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('industry', models.CharField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_jobs', to='account.employer')),
            ],
        ),
    ]
