# Generated by Django 5.1.7 on 2025-03-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empjob', '0002_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'Text Answer'), ('MCQ', 'Multiple Choice'), ('CODE', 'Code Answer')], default='TEXT', max_length=4),
        ),
    ]
