# Generated by Django 5.1.7 on 2025-03-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empjob', '0003_question_options_question_question_type'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyedjobs',
            name='status',
            field=models.CharField(choices=[('Application Send', 'Application Send'), ('Application Viewd', 'Application Viewed'), ('Resume Viewd', 'Resume Viewed')], default='Application Send', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='applyedjobs',
            unique_together={('candidate', 'job')},
        ),
    ]
